In [351]:
import numpy as np
import pandas as pd

Phase 1 : **Data Cleaning.**

In [352]:
#unclean sample data set
data = {
    'Car_Model' : ['Corrola','Civic','Mehran','Corrola','City','Cultus'],
    'Mileage'   : [50000 , np.nan , 20000 ,50000,80000,15000], #np.nan is an empty data (missing)
    'Price'     : [2500000 , 3000000 , 100000,2500000,500000000,1800000] #50cr is an outlier
}
df = pd.DataFrame(data)
print("--- Orignal Messy Data ---")
data

--- Orignal Messy Data ---

{'Car_Model': ['Corrola', 'Civic', 'Mehran', 'Corrola', 'City', 'Cultus'],
 'Mileage': [50000, nan, 20000, 50000, 80000, 15000],
 'Price': [2500000, 3000000, 100000, 2500000, 500000000, 1800000]}

**-Handling Missing Values**

In [353]:
df.isna().sum()

Car_Model    0
Mileage      1
Price        0
dtype: int64

In [354]:
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mean())

In [355]:
df

  Car_Model  Mileage      Price
0   Corrola  50000.0    2500000
1     Civic  43000.0    3000000
2    Mehran  20000.0     100000
3   Corrola  50000.0    2500000
4      City  80000.0  500000000
5    Cultus  15000.0    1800000

**-Handling Duplicates**

In [356]:
df.duplicated().sum()

np.int64(1)

In [357]:
df = df.drop_duplicates()

In [358]:
print('After removing duplicates:\n' , df)

After removing duplicates:
   Car_Model  Mileage      Price
0   Corrola  50000.0    2500000
1     Civic  43000.0    3000000
2    Mehran  20000.0     100000
4      City  80000.0  500000000
5    Cultus  15000.0    1800000

**-Outliers Removing**

In [359]:
#Removing those car with price more then 1cr
df = df[df['Price'] < 10000000]

In [360]:
print('After Removing outliers:\n',df)

After Removing outliers:
   Car_Model  Mileage    Price
0   Corrola  50000.0  2500000
1     Civic  43000.0  3000000
2    Mehran  20000.0   100000
5    Cultus  15000.0  1800000

Phase 2 : **Data Transformation**
**- Encoding Categorical Data**

**(A)** Label Encoding
**(B)** One-hot-Encoding
**(C)** Target Encoding

In [361]:
#Sample Data Set
data = {
    'car' : ['civic' , 'corrola' , 'mehran' ],
    'condition' : ['good' , 'excellent' , 'bad'],
    'fuel' : ['petrol' , 'diesel' , 'cng']
}
df = pd.DataFrame(data)
df

       car  condition    fuel
0    civic       good  petrol
1  corrola  excellent  diesel
2   mehran        bad     cng

In [362]:
#1 : Label Encoding (using .map function for condition column)
condition_mapping = {'good' : 2 , 'excellent' : 3 , 'bad' :1 }
df['condition'] = df['condition'].map(condition_mapping)
df

       car  condition    fuel
0    civic          2  petrol
1  corrola          3  diesel
2   mehran          1     cng

In [363]:
#2 : One-hot-encoding (used for fuel column using get_dumies)
df = pd.get_dummies(df , columns=['fuel'] , dtype= int)
df

       car  condition  fuel_cng  fuel_diesel  fuel_petrol
0    civic          2         0            0            1
1  corrola          3         0            1            0
2   mehran          1         1            0            0

**Target Encoding**

In [364]:
# 1.  Data (includes price/Target columns)
data = {
    'Car': ['Civic', 'Corolla', 'Mehran', 'City'],
    'Condition': ['Good', 'Excellent', 'Bad', 'Good'],
    'Fuel': ['Petrol', 'Diesel', 'CNG', 'Petrol'], # Petrol 2 dafa hai
    'Price': [3000000, 4000000, 800000, 2000000]   # Yeh hamara Target hai
}
df = pd.DataFrame(data)

print("--- Original Data ---")
print(df)

# TARGET ENCODING LOGIC


# Step 1:  Calculating each fule type average price
# groupby('Fuel') and ['Price'].mean()
fuel_target_mean = df.groupby('Fuel')['Price'].mean()

# Step 2: mapping average back to fuel column
df['Fuel_Encoded'] = df['Fuel'].map(fuel_target_mean)
print("\n---  After Target Encoding  ---")
print(df[['Car', 'Condition', 'Fuel', 'Fuel_Encoded', 'Price']])

--- Original Data ---

       Car  Condition    Fuel    Price
0    Civic       Good  Petrol  3000000
1  Corolla  Excellent  Diesel  4000000
2   Mehran        Bad     CNG   800000
3     City       Good  Petrol  2000000

---  After Target Encoding  ---
       Car  Condition    Fuel  Fuel_Encoded    Price
0    Civic       Good  Petrol     2500000.0  3000000
1  Corolla  Excellent  Diesel     4000000.0  4000000
2   Mehran        Bad     CNG      800000.0   800000
3     City       Good  Petrol     2500000.0  2000000

**Feature Scaling**

In [365]:
from sklearn.preprocessing import MinMaxScaler

# Sample Data
num_data = pd.DataFrame({'Age': [2, 5, 10],
                         'Mileage': [20000, 50000, 100000]
                         })

# Intializing scalar
scaler = MinMaxScaler()

#coverting data between 0 and 1
scaled_data = scaler.fit_transform(num_data)

print(scaled_data)

[[0.    0.   ]
 [0.375 0.375]
 [1.    1.   ]]

In [366]:
import pandas as pd

#new sample data
data = {
    'Ad_ID': [101, 102, 103],
    'Owner_Name': ['Ali', 'Hamza', 'Saad'],
    'Car_Name': ['Honda Civic Oriel', 'Toyota Corolla XLI', 'Suzuki Mehran VXR'],
    'Make_Year': [2018, 2021, 2015],
    'Price': [4500000, 4200000, 900000]
}
df = pd.DataFrame(data)

print("--- Original Data ---")
print(df.head())

--- Original Data ---
   Ad_ID Owner_Name            Car_Name  Make_Year    Price
0    101        Ali   Honda Civic Oriel       2018  4500000
1    102      Hamza  Toyota Corolla XLI       2021  4200000
2    103       Saad   Suzuki Mehran VXR       2015   900000

In [367]:
def name_extracter(txt):
    parts = txt.split(' ')
    return parts[0]

In [368]:
df["Model"] = df['Car_Name'].apply(lambda x : x.split(' ')[0])

In [369]:
df['Car_Age'] = 2026 - df['Make_Year']

In [370]:
df = df.drop(columns=['Ad_ID','Owner_Name'])
df

             Car_Name  Make_Year    Price   Model  Car_Age
0   Honda Civic Oriel       2018  4500000   Honda        8
1  Toyota Corolla XLI       2021  4200000  Toyota        5
2   Suzuki Mehran VXR       2015   900000  Suzuki       11