In [42]:
import numpy as np
import pandas as pd

Creating a Data Frame.

In [43]:
data = {
    'Name' : ['John','Anna','Peter','Linda'],
    'Age'  : [28 ,34,29,42],
    'City' : ['New York' ,'Paris','Berlin','London'],
    'Salary' :[65000,70000,62000,85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and indexing of columns.

In [44]:
df["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [45]:
df[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

Creating new column

In [46]:
df["Desigination"] = ["Docter","Enginner","labour","Electircian"]
df

    Name  Age      City  Salary Desigination
0   John   28  New York   65000       Docter
1   Anna   34     Paris   70000     Enginner
2  Peter   29    Berlin   62000       labour
3  Linda   42    London   85000  Electircian

Removing columns.

In [47]:
df.drop("Desigination",axis=1 , inplace=True)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting Rows.

In [48]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [49]:
df.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

Selecting Subsets of Rows and Columns

In [50]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [51]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#I only want to see those peoples whose age is above 30
df[df["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [54]:
#I only want people whose age is above 30 and their city must be paris
df[(df["Age"] > 30) & (df["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000