In [74]:
import numpy as np
import pandas as pd

Finding Missing Data

In [75]:
data = {
    'A' :[1,2,np.nan,4,5],
    'B' :[np.nan,2,3,4,5],
    'C' :[1,2,3,np.nan,np.nan],
    'D' :[1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [76]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [77]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

Removing Missing Data

In [78]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [79]:
df.dropna(axis=0)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [80]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

Filling  the missing Data

In [81]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [82]:
#filling missing values with 0
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [83]:
#fill missing values with different values for each column
values = {'A':100,'B':1200,'C':200 ,'D':21}
df.fillna(value=values)

       A       B      C     D
0    1.0  1200.0    1.0   1.0
1    2.0     2.0    2.0  21.0
2  100.0     3.0    3.0  21.0
3    4.0     4.0  200.0  21.0
4    5.0     5.0  200.0   5.0

In [84]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [85]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0