In [42]:
import numpy as np 
import pandas as pd

**Merging two Data Frames**

In [43]:
#dataframe 1:Employees information
employes = pd.DataFrame({
    'employee_id' : [1,2,3,4,5],
    'name' :['John','Anna','Peter','Linda','Bob'],
    'department' :['HR','IT','Finance', 'IT','HR']
})
#dataframe 2: Salary information
salaries = pd.DataFrame({
    'employee_id' :[1,2,3,6,7],
    'salary' :[1000,1222,2345,5435,453],
    'bonus' :[233,232,54,66,64]
}
)

In [44]:
employes

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [45]:
salaries

   employee_id  salary  bonus
0            1    1000    233
1            2    1222    232
2            3    2345     54
3            6    5435     66
4            7     453     64

In [46]:
pd.merge(employes,salaries ,on='employee_id',how="inner")

   employee_id   name department  salary  bonus
0            1   John         HR    1000    233
1            2   Anna         IT    1222    232
2            3  Peter    Finance    2345     54

In [47]:
pd.merge(employes,salaries ,on='employee_id',how="outer")

   employee_id   name department  salary  bonus
0            1   John         HR  1000.0  233.0
1            2   Anna         IT  1222.0  232.0
2            3  Peter    Finance  2345.0   54.0
3            4  Linda         IT     NaN    NaN
4            5    Bob         HR     NaN    NaN
5            6    NaN        NaN  5435.0   66.0
6            7    NaN        NaN   453.0   64.0

In [48]:
pd.merge(employes,salaries ,on='employee_id',how="left")

   employee_id   name department  salary  bonus
0            1   John         HR  1000.0  233.0
1            2   Anna         IT  1222.0  232.0
2            3  Peter    Finance  2345.0   54.0
3            4  Linda         IT     NaN    NaN
4            5    Bob         HR     NaN    NaN

In [49]:
pd.merge(employes,salaries ,on='employee_id',how="right")

   employee_id   name department  salary  bonus
0            1   John         HR    1000    233
1            2   Anna         IT    1222    232
2            3  Peter    Finance    2345     54
3            6    NaN        NaN    5435     66
4            7    NaN        NaN     453     64

**Concatenation**

In [50]:
employes

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [51]:
salaries

   employee_id  salary  bonus
0            1    1000    233
1            2    1222    232
2            3    2345     54
3            6    5435     66
4            7     453     64

In [52]:
pd.concat([employes,salaries], axis=0, ignore_index= True)

   employee_id   name department  salary  bonus
0            1   John         HR     NaN    NaN
1            2   Anna         IT     NaN    NaN
2            3  Peter    Finance     NaN    NaN
3            4  Linda         IT     NaN    NaN
4            5    Bob         HR     NaN    NaN
5            1    NaN        NaN  1000.0  233.0
6            2    NaN        NaN  1222.0  232.0
7            3    NaN        NaN  2345.0   54.0
8            6    NaN        NaN  5435.0   66.0
9            7    NaN        NaN   453.0   64.0

**Joining**

In [56]:
df1  = pd.DataFrame({
    'name' : ['Ali' , 'Hamza' , 'Zain']
}
)
df2 = pd.DataFrame({
    'marks' :[10,20,30,40]
})

In [58]:
df1.join(df2 , how='outer')

    name  marks
0    Ali     10
1  Hamza     20
2   Zain     30
3    NaN     40