In [392]:
import numpy as np
import pandas as pd

In [393]:
#Loading data
df = pd.read_csv('anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [394]:
#Checking null values
df.isna().sum()

Rank     0
Title    0
Score    0
dtype: int64

In [395]:
#1.Make a new column for episode count.
def extract_episode(txt):
    check = False
    data = ''
    for i in txt:
        if i == ')':
            check = False
            return data
        if check == True:
            data += i
        if i == '(' :
            check = True

In [396]:
df['Episodes']=df['Title'].apply(extract_episode)
df['Episodes']=df['Episodes'].str.replace(" eps" , "")
df['Episodes']=df['Episodes'].astype(int)

In [397]:
#Make a new column for timestamp.
def extract_time(txt):
    data = ''
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range(i+1, i+20):
                data +=txt[j]
                
            return data

In [398]:
df['Time_Stamp']=df['Title'].apply(extract_time)

In [399]:
#Extract Months from time stamp
def calculate_months(time_str):
   parts = str(time_str).split('-')
   if len(parts) != 2:
       return None
   start_date = pd.to_datetime(parts[0].strip(), format= '%b %Y')
   end_date = pd.to_datetime(parts[1].strip(),format= '%b %Y')
   total_months = (end_date.year- start_date.year) * 12 + (end_date.month - start_date.month)
   return total_months
   df

In [400]:
df['Total Months'] = df['Time_Stamp'].apply(calculate_months)
df.head()

,Rank,Title,Score,Episodes,Time_Stamp,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [401]:
#Which anime has highest score
df.loc[df['Score'].idxmax(),'Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [402]:
#Give me top 5 highest scoring anime
df.nlargest(5,'Score')

,Rank,Title,Score,Episodes,Time_Stamp,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [403]:
#Which anime has the highest episode count
df.loc[df['Episodes'].idxmax()]['Title']

'GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members'

In [404]:
#animes with top 5 episode count
df.nlargest(5 ,'Episodes')

,Rank,Title,Score,Episodes,Time_Stamp,Total Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,35
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,17
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,17

In [405]:
#Which is the longest running anime
df.loc[df['Total Months'].idxmax() ]['Title']

'Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members'